### ISSUE TITLE
Allow disabling logs by redefining ggprintf macro

### ISSUE THREAD

**Issue by petrdvorak** [ggerganov/ggwave-spm#4]
Currently, the code in `ggwave.cpp` is always logging. Sometimes (especially in production builds), this could be undesired. It would be nice to disable logging, i.e., based on additional environment variable or in case DEBUG is not defined.

**Comment by ggerganov** [comment]
You can disable ggwave logging by calling the `ggwave_setLogFile()` function. Here is an example how to use it:

https://github.com/ggerganov/ggwave-objc/commit/f64bae236884c675642d23af6597096201d03a53

**Comment by petrdvorak** [comment]
Thank you, I will have a look. The issue of this approach, though, is that logging is configured at runtime. With macro definition, the logging code is rmeoved at compile time.
